# This is a basic workflow to help you get started with Actions

name: production

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: checking out codebase
        uses: actions/checkout@v2

      - name: dependencies installation
        run: npm i

      - name: building production bundle
        run: npm run build-prod -- --env basename=/entropy/ --env output=dist

      - name: deploying to github pages
        uses: crazy-max/ghaction-github-pages@v2.2.0
        with:
          build_dir: dist
          target_branch: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
